name: CI
on: [push, pull_request]

jobs:
  validate:
    name: Validate outputs
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          version: ${{ matrix.version }}
