name: CI
on: [push, pull_request]

jobs:
  validate:
    name: Validate outputs
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [stable, nightly, v8.1.2424, v0.4.0]
        neovim: [true, false]
        exclude:
          - neovim: true
            version: v8.1.2424
            os: ubuntu-latest
          - neovim: true
            version: v8.1.2424
            os: macos-latest
          - neovim: true
            version: v8.1.2424
            os: windows-latest
          - neovim: false
            version: v0.4.0
            os: ubuntu-latest
          - neovim: false
            version: v0.4.0
            os: macos-latest
          - neovim: false
            version: v0.4.0
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          version: ${{ matrix.version }}
          neovim: ${{ matrix.neovim }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: vim
      - name: Validate action result
        run: node ./scripts/post_action_check.js "${{ matrix.neovim }}" "${{ matrix.version }}" "${{ steps.vim.outputs.executable }}"

  test-and-lint:
    name: Check unit tests and linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - uses: actions/setup-python@v1
      - run: pip install yamllint
      - run: yamllint --strict .github/workflows
