name: Post-release check
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - 'CHANGELOG.md'
      - '.github/workflows/released.yml'

jobs:
  validate:
    name: Validate release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        neovim: [true, false]
        version: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: ${{ matrix.version }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g ts-node typescript @types/node
      - name: Validate action result
        run: ts-node ./scripts/post_action_check.ts "${{ matrix.neovim }}" "${{ matrix.version }}" "${{ steps.vim.outputs.executable }}"
