name: Smoke test
on:
  push:
    branches:
      - master

jobs:
  validate:
    name: Validate release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        neovim: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: ${{ matrix.neovim }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
